export interface Benefit {
  id: string;
  assetId: string;
  title: string;
  description: string;
  level: 'bronze' | 'silver' | 'gold' | 'platinum' | 'diamond';
  investmentRequired: string;
  tier?: string;
  includesPrevious?: boolean;
}

export const benefits: Benefit[] = [
  // Liverpool FC Benefits
  {
    id: 'liverpool-1',
    assetId: 'liverpool',
    title: 'Digital Collectible + Exclusive Content',
    description: 'Exclusive digital collectible NFT of your ownership plus access to behind-the-scenes content',
    level: 'bronze',
    investmentRequired: '£500-£2,000',
  },
  {
    id: 'liverpool-2',
    assetId: 'liverpool',
    title: 'Stadium Tour',
    description: 'Private guided tour of Anfield stadium',
    level: 'silver',
    investmentRequired: '£2,001-£5,000',
    includesPrevious: true,
  },
  {
    id: 'liverpool-3',
    assetId: 'liverpool',
    title: 'VIP Match Experience',
    description: 'Premium seating and hospitality for one home match per season',
    level: 'gold',
    investmentRequired: '£5,001-£15,000',
    includesPrevious: true,
  },
  {
    id: 'liverpool-4',
    assetId: 'liverpool',
    title: 'Training Ground Visit',
    description: 'Annual visit to AXA Training Centre and meet the players',
    level: 'platinum',
    investmentRequired: '£15,001-£50,000',
    includesPrevious: true,
  },
  {
    id: 'liverpool-5',
    assetId: 'liverpool',
    title: 'Board Meeting Access',
    description: 'Invitation to annual shareholder meeting and club events',
    level: 'diamond',
    investmentRequired: '£50,000+',
    includesPrevious: true,
  },
  
  // McLaren Benefits
  {
    id: 'mclaren-1',
    assetId: 'mclaren',
    title: 'Exclusive Content',
    description: 'Behind-the-scenes content and team updates',
    level: 'bronze',
    investmentRequired: '£1,000-£5,000',
  },
  {
    id: 'mclaren-2',
    assetId: 'mclaren',
    title: 'McLaren Merchandise',
    description: 'Limited edition McLaren Racing merchandise package',
    level: 'silver',
    investmentRequired: '£5,001-£15,000',
    includesPrevious: true,
  },
  {
    id: 'mclaren-3',
    assetId: 'mclaren',
    title: 'Paddock Club Access',
    description: 'Access to the McLaren Paddock Club at one race per season',
    level: 'gold',
    investmentRequired: '£15,001-£50,000',
    includesPrevious: true,
  },
  {
    id: 'mclaren-4',
    assetId: 'mclaren',
    title: 'Factory Tour',
    description: 'Private tour of McLaren Technology Centre',
    level: 'platinum',
    investmentRequired: '£50,001-£100,000',
    includesPrevious: true,
  },
  {
    id: 'mclaren-5',
    assetId: 'mclaren',
    title: 'Meet Lando Norris',
    description: 'Private meet-and-greet with Lando Norris at a race weekend',
    level: 'diamond',
    investmentRequired: '£100,000+',
    includesPrevious: true,
  },
  
  // Ryder Cup Benefits
  {
    id: 'rydercup-1',
    assetId: 'rydercup',
    title: 'Commemorative Merchandise',
    description: 'Limited edition Ryder Cup merchandise package and certificate',
    level: 'bronze',
    investmentRequired: '£5,000',
  },
  {
    id: 'rydercup-2',
    assetId: 'rydercup',
    title: 'Premium Hospitality',
    description: 'Access to Silver Club hospitality areas during practice rounds',
    level: 'silver',
    investmentRequired: '£15,000',
    includesPrevious: true,
  },
  {
    id: 'rydercup-3',
    assetId: 'rydercup',
    title: 'Exclusive Tournament Access',
    description: 'Premium seating for all tournament days plus Gold Lounge Access',
    level: 'gold',
    investmentRequired: '£25,000',
    includesPrevious: true,
  },
  {
    id: 'rydercup-4',
    assetId: 'rydercup',
    title: 'Player Meet & Greet',
    description: 'Exclusive meet and greet with Ryder Cup players',
    level: 'platinum',
    investmentRequired: '£35,000',
    includesPrevious: true,
  },
  {
    id: 'rydercup-5',
    assetId: 'rydercup',
    title: 'Captain\'s Dinner',
    description: 'Exclusive dinner with the Ryder Cup Captain and team members',
    level: 'diamond',
    investmentRequired: '£50,000',
    includesPrevious: true,
  },

  // Ohio State Benefits
  {
    id: 'ohio-1',
    assetId: 'ohio',
    title: 'Buckeye Digital Package',
    description: 'Exclusive Ohio State digital content and stadium renovation updates',
    level: 'bronze',
    investmentRequired: '£2,500-£7,500',
  },
  {
    id: 'ohio-2',
    assetId: 'ohio',
    title: 'Stadium Tour Access',
    description: 'Private tour of renovated Ohio Stadium facilities',
    level: 'silver',
    investmentRequired: '£7,501-£20,000',
    includesPrevious: true,
  },
  {
    id: 'ohio-3',
    assetId: 'ohio',
    title: 'Game Day Experience',
    description: 'Premium seating and hospitality for one home game per season',
    level: 'gold',
    investmentRequired: '£20,001-£50,000',
    includesPrevious: true,
  },
  {
    id: 'ohio-4',
    assetId: 'ohio',
    title: 'Athletic Department Access',
    description: 'Meet coaches and players at exclusive events',
    level: 'platinum',
    investmentRequired: '£50,001-£100,000',
    includesPrevious: true,
  },
  {
    id: 'ohio-5',
    assetId: 'ohio',
    title: 'Legacy Donor Status',
    description: 'Permanent recognition and access to all university athletic events',
    level: 'diamond',
    investmentRequired: '£100,000+',
    includesPrevious: true,
  },

  // Cardiff City Benefits
  {
    id: 'cardiff-1',
    assetId: 'cardiff',
    title: 'Bluebirds Digital Access',
    description: 'Exclusive Cardiff City content and behind-the-scenes footage',
    level: 'bronze',
    investmentRequired: '£1,000-£3,000',
  },
  {
    id: 'cardiff-2',
    assetId: 'cardiff',
    title: 'Cardiff City Stadium Tour',
    description: 'Private tour of Cardiff City Stadium and training facilities',
    level: 'silver',
    investmentRequired: '£3,001-£8,000',
    includesPrevious: true,
  },
  {
    id: 'cardiff-3',
    assetId: 'cardiff',
    title: 'Match Day Hospitality',
    description: 'Premium seating and hospitality for home matches',
    level: 'gold',
    investmentRequired: '£8,001-£20,000',
    includesPrevious: true,
  },
  {
    id: 'cardiff-4',
    assetId: 'cardiff',
    title: 'Player Meet & Greet',
    description: 'Exclusive access to meet Cardiff City players and management',
    level: 'platinum',
    investmentRequired: '£20,001-£50,000',
    includesPrevious: true,
  },
  {
    id: 'cardiff-5',
    assetId: 'cardiff',
    title: 'Board Room Access',
    description: 'Invitation to board meetings and strategic planning sessions',
    level: 'diamond',
    investmentRequired: '£50,000+',
    includesPrevious: true,
  },

  // Hexagon Fan Team Benefits
  {
    id: 'hexagon-1',
    assetId: 'hexagon',
    title: 'Fan Team Membership',
    description: 'Official Hexagon Fan Team membership with exclusive content access',
    level: 'bronze',
    investmentRequired: '£500-£2,000',
  },
  {
    id: 'hexagon-2',
    assetId: 'hexagon',
    title: 'Creator Studio Access',
    description: 'Behind-the-scenes access to content creation and fan engagement activities',
    level: 'silver',
    investmentRequired: '£2,001-£5,000',
    includesPrevious: true,
  },
  {
    id: 'hexagon-3',
    assetId: 'hexagon',
    title: 'VIP Event Access',
    description: 'Exclusive access to Hexagon Fan Team events and meet-ups',
    level: 'gold',
    investmentRequired: '£5,001-£15,000',
    includesPrevious: true,
  },
  {
    id: 'hexagon-4',
    assetId: 'hexagon',
    title: 'Content Collaboration',
    description: 'Opportunity to collaborate on content creation with the team',
    level: 'platinum',
    investmentRequired: '£15,001-£30,000',
    includesPrevious: true,
  },
  {
    id: 'hexagon-5',
    assetId: 'hexagon',
    title: 'Strategic Partnership',
    description: 'Direct input on fan engagement strategy and revenue sharing',
    level: 'diamond',
    investmentRequired: '£30,000+',
    includesPrevious: true,
  },

  // Exeter Rugby Benefits
  {
    id: 'exeter-rugby-1',
    assetId: 'exeter-rugby',
    title: 'Chiefs Digital Package',
    description: 'Exclusive Exeter Chiefs digital content and match highlights',
    level: 'bronze',
    investmentRequired: '£500-£2,000',
  },
  {
    id: 'exeter-rugby-2',
    assetId: 'exeter-rugby',
    title: 'Sandy Park Stadium Tour',
    description: 'Private guided tour of Sandy Park stadium and training facilities',
    level: 'silver',
    investmentRequired: '£2,001-£5,000',
    includesPrevious: true,
  },
  {
    id: 'exeter-rugby-3',
    assetId: 'exeter-rugby',
    title: 'Match Day Hospitality',
    description: 'Premium seating and hospitality for Premiership home matches',
    level: 'gold',
    investmentRequired: '£5,001-£15,000',
    includesPrevious: true,
  },
  {
    id: 'exeter-rugby-4',
    assetId: 'exeter-rugby',
    title: 'Player Meet & Greet',
    description: 'Exclusive meet and greet with Exeter Chiefs players and coaching staff',
    level: 'platinum',
    investmentRequired: '£15,001-£30,000',
    includesPrevious: true,
  },
  {
    id: 'exeter-rugby-5',
    assetId: 'exeter-rugby',
    title: 'Chiefs Inner Circle',
    description: 'Access to board meetings and strategic planning sessions with club leadership',
    level: 'diamond',
    investmentRequired: '£30,000+',
    includesPrevious: true,
  },

  // British Cycling Benefits
  {
    id: 'british-cycling-1',
    assetId: 'british-cycling',
    title: 'Cycling Digital Access',
    description: 'Exclusive British Cycling content and Tour of Britain behind-the-scenes footage',
    level: 'bronze',
    investmentRequired: '£1,000-£3,000',
  },
  {
    id: 'british-cycling-2',
    assetId: 'british-cycling',
    title: 'Velodrome Experience',
    description: 'Private track session at Manchester Velodrome with coaching',
    level: 'silver',
    investmentRequired: '£3,001-£7,500',
    includesPrevious: true,
  },
  {
    id: 'british-cycling-3',
    assetId: 'british-cycling',
    title: 'Tour of Britain VIP Access',
    description: 'Premium hospitality and VIP access to Tour of Britain stages',
    level: 'gold',
    investmentRequired: '£7,501-£20,000',
    includesPrevious: true,
  },
  {
    id: 'british-cycling-4',
    assetId: 'british-cycling',
    title: 'Elite Rider Meet & Greet',
    description: 'Exclusive access to meet British Cycling elite riders and coaching staff',
    level: 'platinum',
    investmentRequired: '£20,001-£40,000',
    includesPrevious: true,
  },
  {
    id: 'british-cycling-5',
    assetId: 'british-cycling',
    title: 'Performance Centre Access',
    description: 'Annual visit to British Cycling Performance Centre and training camps',
    level: 'diamond',
    investmentRequired: '£40,000+',
    includesPrevious: true,
  },

  // Ultimate Frisbee Association Benefits
  {
    id: 'ultimate-frisbee-1',
    assetId: 'ultimate-frisbee',
    title: 'UFA Digital Membership',
    description: 'Exclusive Ultimate Frisbee Association content and tournament highlights',
    level: 'bronze',
    investmentRequired: '£250-£1,000',
  },
  {
    id: 'ultimate-frisbee-2',
    assetId: 'ultimate-frisbee',
    title: 'Team Training Access',
    description: 'Access to professional team training sessions and coaching clinics',
    level: 'silver',
    investmentRequired: '£1,001-£3,000',
    includesPrevious: true,
  },
  {
    id: 'ultimate-frisbee-3',
    assetId: 'ultimate-frisbee',
    title: 'Championship Tournament VIP',
    description: 'VIP access to Ultimate Frisbee championship tournaments and finals',
    level: 'gold',
    investmentRequired: '£3,001-£8,000',
    includesPrevious: true,
  },
  {
    id: 'ultimate-frisbee-4',
    assetId: 'ultimate-frisbee',
    title: 'Player Development Programme',
    description: 'Exclusive access to player development programmes and elite coaching',
    level: 'platinum',
    investmentRequired: '£8,001-£20,000',
    includesPrevious: true,
  },
  {
    id: 'ultimate-frisbee-5',
    assetId: 'ultimate-frisbee',
    title: 'League Partnership',
    description: 'Strategic partnership role in league development and expansion decisions',
    level: 'diamond',
    investmentRequired: '£20,000+',
    includesPrevious: true,
  },
];